#include "consts.h"

OBJ_ATTR *pipeSprites[MAX_PIPES][MAX_VERT_PIPES] = {
  {
    PIPE_ZERO_0,
    PIPE_ZERO_1,
    PIPE_ZERO_2,
    PIPE_ZERO_3,
    PIPE_ZERO_4,
    PIPE_ZERO_5,
    PIPE_ZERO_6,
    // PIPE_ZERO_7,
  },
  {
    PIPE_ONE_0,
    PIPE_ONE_1,
    PIPE_ONE_2,
    PIPE_ONE_3,
    PIPE_ONE_4,
    PIPE_ONE_5,
    PIPE_ONE_6,
    // PIPE_ONE_7,
  },
  {
    PIPE_TWO_0,
    PIPE_TWO_1,
    PIPE_TWO_2,
    PIPE_TWO_3,
    PIPE_TWO_4,
    PIPE_TWO_5,
    PIPE_TWO_6,
    // PIPE_TWO_7,
  },
  {
    PIPE_THREE_0,
    PIPE_THREE_1,
    PIPE_THREE_2,
    PIPE_THREE_3,
    PIPE_THREE_4,
    PIPE_THREE_5,
    PIPE_THREE_6,
    // PIPE_THREE_7,
  },
  {
    PIPE_FOUR_0,
    PIPE_FOUR_1,
    PIPE_FOUR_2,
    PIPE_FOUR_3,
    PIPE_FOUR_4,
    PIPE_FOUR_5,
    PIPE_FOUR_6,
    // PIPE_FOUR_7,
  },
  {
    PIPE_FIVE_0,
    PIPE_FIVE_1,
    PIPE_FIVE_2,
    PIPE_FIVE_3,
    PIPE_FIVE_4,
    PIPE_FIVE_5,
    PIPE_FIVE_6,
    // PIPE_FIVE_7,
  },
/*   {
    PIPE_SIX_0,
    PIPE_SIX_1,
    PIPE_SIX_2,
    PIPE_SIX_3,
    PIPE_SIX_4,
    PIPE_SIX_5,
    PIPE_SIX_6,
    PIPE_SIX_7,
  },
  {
    PIPE_SIX_0,
    PIPE_SIX_1,
    PIPE_SIX_2,
    PIPE_SIX_3,
    PIPE_SIX_4,
    PIPE_SIX_5,
    PIPE_SIX_6,
    PIPE_SIX_7,
  } */
};
